# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 08:22
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Account number, 8 digits', unique=True, validators=[accounts.models.validate_8digits])),
                ('currency', models.CharField(choices=[('USD', 'USD: US dollar'), ('EUR', 'EUR: Euro'), ('GBP', 'GBP: British pound'), ('CHF', 'CHF: Swiss frank')], max_length=3)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
