# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('op_type', models.CharField(choices=[('dep', 'Deposit (add money)'), ('wd', 'Withdrawal (take money)'), ('tra', 'Transfer (move money)')], max_length=3, verbose_name='Operation type')),
                ('source_amount', models.FloatField(blank=True, help_text="Amount in source account's currency, or in withdrawal account's currency. Not used in deposits", null=True)),
                ('dest_amount', models.FloatField(blank=True, help_text="Amount in destination account's currency, or in deposit account's currency. Not used in withdrawals", null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('dest_acc', models.ForeignKey(blank=True, help_text='Used in transfers; must be blank for withdrawals', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_with_this_dest', to='accounts.Account', verbose_name='Destination account')),
                ('source_acc', models.ForeignKey(blank=True, help_text='Used in transfers; must be blank for deposits', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_with_this_source', to='accounts.Account', verbose_name='Source account')),
            ],
        ),
    ]
