# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 09:33
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text='Account number, 8 digits', unique=True, validators=[accounts.models.validate_8digits]),
        ),
    ]
