# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170602_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0, help_text='Latest balance'),
        ),
    ]
