# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=5, default=0, help_text='Latest balance', max_digits=17),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='dest_amount',
            field=models.DecimalField(blank=True, decimal_places=5, help_text="Amount in destination account's currency, or in deposit account's currency. Not used in withdrawals", max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_amount',
            field=models.DecimalField(blank=True, decimal_places=5, help_text="Amount in source account's currency, or in withdrawal account's currency. Not used in deposits", max_digits=17, null=True),
        ),
    ]
